### ISSUE TITLE
failed to self host

### ISSUE THREAD

**Issue by rain-1** [orodley/naive#2]
Hi! With my modifications I could build the compiler from my host, but i could not do a self hosted build. Here is how I attempted to do it:

```
make DESTDIR=bin-host
export PATH=$PATH:`pwd`/bin-host/
make clean
make DESTDIR=bin-selfhost CC=naive AR=nar ASM=nas
```

I would appreciate your input if what I am trying is correct, and what I should attempt to resolve the error:

```
PEG src/parse.peg
ENC src/x64.enc
CC src/bin/ncc.c
src/bin/ncc.c:4:10: Error: File not found: 'assert.h'
```

I looked for assert and there is some: 

```
$ find . | grep assert
./libc/assert.c
./libc/include/assert.h
./bin-host/include/assert.h
./tests/ncc/assert_true
./tests/ncc/assert_true/in.c
```

**Comment by rain-1** [comment]
I figured out that the reason this happened was because `/opt/bin` is hard coded in `./src/bin/ncc.c`. I wanted to change it to use getenv but the stdlib doesn't have getenv. So temporarily hard coded it to my own path. I now get this error:

```
PEG src/parse.peg
ENC src/x64.enc
CC src/bin/ncc.c
CC src/array.c
CC src/asm.c
CC src/asm_gen.c
CC src/bit_set.c
CC src/diagnostics.c
CC src/elf.c
CC src/file.c
CC src/ir.c
CC src/ir_gen.c
CC src/parse.c
CC src/pool.c
CC src/preprocess.c
CC src/reader.c
CC src/tokenise.c
CC src/util.c
CC ncc
Relocations for that section are not supported (found rela section .rela.data.rel.local)
Relocations for that section are not supported (found rela section .rela.data.rel.local)
Relocations for that section are not supported (found rela section .rela.data.rel.local)
Relocations for that section are not supported (found rela section .rela.rodata)
Undefined symbol 'stdout'
Linker error, terminating
make: *** [Makefile:67: ncc] Error 10
```

**Comment by rain-1** [comment]
I can reproduced the error with `out/naive -dump-ast -Isrc src/bin/ncc.c` as well as `out/naive -Isrc src/bin/ncc.c`.

So I am starting to think maybe the initial compile produced a faulty binary.  I am not sure if I need to add some special linker flags or something.

**Comment by orodley** [comment]
The issue in your second comment is familiar. The ncc linker is basically only designed to handle object files generated by ncc. In particular it can only handle relocation sections for a fixed list of associated sections (`.rela.text` and `.rela.data`). The sections in that error message are neither of these, so the link fails.

We use the system compiler to compile our libc, and then we use ncc to compile itself and link against that libc. Because of how limited the linker is, we need to take special care to make sure that the host compiler produces binaries the linker can actually handle. This is what the `-fno-asynchronous-unwind-tables` and `-fno-common` flags are for in `LIBC_CFLAGS`, and it's also why we have some hacks like in `perror.c`.

This isn't portable at all, so it's not too surprising that it would break on a different toolchain. It looks like gcc produces some sections (`.data.rel.local` and `.rela.data.rel.local`) for `stdout.c` that we can't handle. There are a few options to deal with this:
1) Add some more hacks to support your toolchain. Either by adding flags or working around in our libc code. This may or may not be possible - gcc might just always produce these sections regardless of what we do. And even if it is possible, it will inevitably still be broken on someone else's toolchain. Still, as a short-term workaround this might be okay.
2) Make the bootstrap process more robust by avoiding passing a host-compiled libc to ncc in the first place. We could do this by adding an extra step in `self_host.sh` - before compiling ncc2, use ncc1 to build just libc.a. Then use this in place of the host-compiled libc.a when compiling ncc2.

Feel free to give either a try. I might look into option 2 later this week if you haven't already.

Hope that helps.

**Comment by rain-1** [comment]
Thank you very much for taking the time to explain this to me, It is very interesting to learn about these details of the compiler. I had been searching about relocatable sections but made no progress understanding the problem. What you wrote made it very easy to understand how this problem came about.
